version: '3.3'
services:
  app:
    container_name: fitness-app-container
    image: fitness-app-image
    build: ./
    ports:
      - "8084:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    container_name: fitnes-server
    image: postgres
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fitnes